import type {Metadata} from "next";
import {Epilogue} from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/layouts/sidebar";
import Header from "@/components/layouts/header";
import {Toaster} from "@/components/ui/toaster";
import {getSession} from "next-auth/react";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";
import {getServerSession} from "next-auth";
import {redirect} from "next/navigation";

const epilogue = Epilogue({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions)

    if (session !== null) {
        return redirect('/')
    }
    return (
        <html lang="en">
        <body className={epilogue.className}>
        <main>
            {children}
        </main>
        <Toaster/>
        </body>
        </html>
    );
}
